version: '3.5'

networks:
  backend:
    name: backend

volumes:
  data-postgre:

services:
  postgresql:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      - data-postgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend


  yumrush:
    image: netkovjordan/yumrush:2.0
    container_name: yumrush-food-delivery-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
     - backend

    

